UPDATE parts SET specs = specs || '{"price": 240}' WHERE model = 'i5-13600K';
UPDATE parts SET specs = specs || '{"price": 290}' WHERE model = 'i7-13700K';
UPDATE parts SET specs = specs || '{"price": 400}' WHERE model = 'i9-13900K';
UPDATE parts SET specs = specs || '{"price": 165}' WHERE model = 'i5-12600K';
UPDATE parts SET specs = specs || '{"price": 195}' WHERE model = 'Ryzen 5 7600X';
UPDATE parts SET specs = specs || '{"price": 279}' WHERE model = 'Ryzen 7 7700X';
UPDATE parts SET specs = specs || '{"price": 349}' WHERE model = 'Ryzen 9 7900X';
UPDATE parts SET specs = specs || '{"price": 529}' WHERE model = 'Ryzen 9 7950X';
UPDATE parts SET specs = specs || '{"price": 249}' WHERE model = 'ROG Strix Z690-A';
UPDATE parts SET specs = specs || '{"price": 149}' WHERE model = 'MAG B660 Tomahawk';
UPDATE parts SET specs = specs || '{"price": 89}'  WHERE model = 'B660M DS3H';
UPDATE parts SET specs = specs || '{"price": 349}' WHERE model = 'ProArt Z790-Creator';
UPDATE parts SET specs = specs || '{"price": 449}' WHERE model = 'MEG X670E ACE';
UPDATE parts SET specs = specs || '{"price": 179}' WHERE model = 'B650 Aorus Elite';
UPDATE parts SET specs = specs || '{"price": 549}' WHERE model = 'ROG Crosshair X670E';
UPDATE parts SET specs = specs || '{"price": 129}' WHERE model = 'B650M Pro RS';
UPDATE parts SET specs = specs || '{"price": 35}'  WHERE model = 'Vengeance DDR4-3200';
UPDATE parts SET specs = specs || '{"price": 59}'  WHERE model = 'Trident Z DDR4-3600';
UPDATE parts SET specs = specs || '{"price": 29}'  WHERE model = 'Fury Beast DDR4-3200';
UPDATE parts SET specs = specs || '{"price": 89}'  WHERE model = 'Dominator DDR5-5200';
UPDATE parts SET specs = specs || '{"price": 109}' WHERE model = 'Trident Z5 DDR5-6000';
UPDATE parts SET specs = specs || '{"price": 55}'  WHERE model = 'Fury Beast DDR5-5200';
UPDATE parts SET specs = specs || '{"price": 340}' WHERE model = 'RTX 4060';
UPDATE parts SET specs = specs || '{"price": 649}' WHERE model = 'RTX 4070';
UPDATE parts SET specs = specs || '{"price": 849}' WHERE model = 'RTX 4070 Ti';
UPDATE parts SET specs = specs || '{"price": 1299}' WHERE model = 'RTX 4080';
UPDATE parts SET specs = specs || '{"price": 300}' WHERE model = 'RX 7600';
UPDATE parts SET specs = specs || '{"price": 419}' WHERE model = 'RX 7700 XT';
UPDATE parts SET specs = specs || '{"price": 949}' WHERE model = 'RX 7900 XTX';
UPDATE parts SET specs = specs || '{"price": 94}'  WHERE model = 'RM650x';
UPDATE parts SET specs = specs || '{"price": 109}' WHERE model = 'RM750x';
UPDATE parts SET specs = specs || '{"price": 129}' WHERE model = 'Focus GX-850';
UPDATE parts SET specs = specs || '{"price": 189}' WHERE model = 'Dark Power 1000W';
UPDATE parts SET specs = specs || '{"price": 99}'  WHERE model = 'SuperNOVA 750 G6';
UPDATE parts SET specs = specs || '{"price": 129}' WHERE model = 'Meshify 2';
UPDATE parts SET specs = specs || '{"price": 139}' WHERE model = 'PC-O11 Dynamic';
UPDATE parts SET specs = specs || '{"price": 79}'  WHERE model = 'H510';
UPDATE parts SET specs = specs || '{"price": 49}'  WHERE model = 'MasterBox Q300L';
UPDATE parts SET specs = specs || '{"price": 69}'  WHERE model = 'Pop Mini';